### ISSUE TITLE
Doesn't work with Gradle 2.4

### ISSUE THREAD

**Issue by JakeWharton** [nebula-plugins/nebula-core#5]
```
Caused by: java.lang.NoClassDefFoundError: org/gradle/listener/BroadcastDispatch
	at nebula.plugin.rxjavaproject.RxjavaProjectPlugin.apply(RxjavaProjectPlugin.groovy:73)
	at nebula.plugin.rxjavaproject.RxjavaProjectPlugin.apply(RxjavaProjectPlugin.groovy)
	at org.gradle.api.internal.plugins.ImperativeOnlyPluginApplicator.applyImperative(ImperativeOnlyPluginApplicator.java:35)
	at org.gradle.api.internal.plugins.RuleBasedPluginApplicator.applyImperative(RuleBasedPluginApplicator.java:43)
	at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:144)
	at org.gradle.api.internal.plugins.DefaultPluginManager.apply(DefaultPluginManager.java:112)
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.applyType(DefaultObjectConfigurationAction.java:113)
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.access$200(DefaultObjectConfigurationAction.java:36)
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction$3.run(DefaultObjectConfigurationAction.java:80)
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.execute(DefaultObjectConfigurationAction.java:136)
	at org.gradle.api.internal.project.AbstractPluginAware.apply(AbstractPluginAware.java:46)
	at org.gradle.api.plugins.PluginAware$apply.call(Unknown Source)
	at org.gradle.api.internal.project.ProjectScript.apply(ProjectScript.groovy:34)
	at org.gradle.api.Script$apply$0.callCurrent(Unknown Source)
	at build_4fxddhtwgd5lnes6p4vp7kosx.run(/Users/jw/dev/other/RxAndroid/build.gradle:14)
	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:74)
	... 38 more
Caused by: java.lang.ClassNotFoundException: org.gradle.listener.BroadcastDispatch
	... 54 more
```
The exception looks like it's [`RxjavaProjectPlugin`][2] related, but the [line in question][1] is:
```groovy
def gradleHelper = new GradleHelper((AbstractProject) project)
```
which is triggering class load of [`GradleHelper`][3] from this project which [references][4] the offending class.

The cause is that Gradleware apparently [breaks public APIs][5] in minor releases:
```diff
  * limitations under the License.
  */
 
-package org.gradle.listener;
+package org.gradle.internal.event;
 
 import org.gradle.api.Action;
 import org.gradle.internal.UncheckedException;
```

 [1]: https://github.com/nebula-plugins/gradle-rxjava-project-plugin/blob/gradle-2.2/src/main/groovy/nebula/plugin/rxjavaproject/RxjavaProjectPlugin.groovy#L73
 [2]: https://github.com/nebula-plugins/gradle-rxjava-project-plugin/blob/gradle-2.2/src/main/groovy/nebula/plugin/rxjavaproject/RxjavaProjectPlugin.groovy
 [3]: https://github.com/nebula-plugins/nebula-core/blob/gradle-2.2/src/main/groovy/nebula/core/GradleHelper.groovy
 [4]: https://github.com/nebula-plugins/nebula-core/blob/gradle-2.2/src/main/groovy/nebula/core/GradleHelper.groovy#L15
 [5]: https://github.com/gradle/gradle/commit/736d8d7be3d3d7018cd26f42dfa3205c247ad997#diff-c9923831272cb8e0db6f5c99d70040a9

**Comment by guoleihit** [comment]
how to resolve this issue ?
